// template-vue-ts/src/popup/components/HelloWorld.vue
<script setup lang="ts">
import { ref } from 'vue'

defineProps({
  msg: String,
})

const count = ref(0)
</script>

<template>
  <h1>{{ msg }}</h1>

  <div class="card">
    <button type="button" @click="count++">
      count is {{ count }}
    </button>
    <p>
      Edit
      <code>src/popup/components/HelloWorld.vue</code> to test HMR
    </p>
  </div>

  <p>
    Check out
    <a href="https://github.com/crxjs/create-crxjs" target="_blank">create-crxjs</a>, the official starter
  </p>

  <p class="read-the-docs">
    Click on the Vite, Vue and CRXJS logos to learn more
  </p>
</template>

<style scoped>
.read-the-docs {
  color: #888;
}
</style>

// template-svelte/src/popup/components/HelloWorld.svelte
<script>
  import { writable } from 'svelte/store'

  export let msg
  const count = writable(0)
</script>

<h1>{msg}</h1>

<div class='card'>
  <button type='button' on:click={() => $count++}>
    count is {$count}
  </button>
  <p>
    Edit
    <code>src/popup/components/HelloWorld.svelte</code> to test HMR
  </p>
</div>

<p>
  Check out
  <a href='https://github.com/crxjs/create-crxjs' target='_blank'>create-crxjs</a>, the official starter
</p>

<p class='read-the-docs'>
  Click on the Vite, Svelte and CRXJS logos to learn more
</p>

<style>
  .read-the-docs {
    color: #888;
  }
</style>
